# Site settings
title: CoppelDev
email: sangulo@coppel.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/test" # the subpath of your site, e.g. /blog/
url: "http://coppeldev.github.io" # the base hostname & protocol for your site
twitter_username: coppeldev
github_username:  coppeldev
exclude: [Gemfile, Gemfile.lock, Procfile]
encoding: utf-8

# Build settings
markdown: redcarpet
